services:

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil_node

    entrypoint: ["anvil"]

    command:
      - --host
      - 0.0.0.0
      - --port
      - "8545"

    ports:
      - "8545:8545"

    networks:
      - blockchain-ipfs-network

    restart: unless-stopped

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_node

    environment:
      - IPFS_PATH=/data/ipfs

    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"

    volumes:
      - ipfs_production_data:/data/ipfs

    networks:
      - blockchain-ipfs-network

    restart: unless-stopped

volumes:
  ipfs_production_data:

networks:
  blockchain-ipfs-network:
    driver: bridge
